# Dockerfile.train



FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
COPY preprocess_data.py .
COPY .env .

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    git \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt


ENV MLFLOW_TRACKING_URI=mlflow+https://dagshub.com/fbarulli/MLOPS-DataTalks.mlflow
ENV MLFLOW_TRACKING_USERNAME=fbarulli
ENV MLFLOW_TRACKING_TOKEN=71f26894d16c0acc62defa4c841c90f2f2ae4716
ENV MLFLOW_TRACKING_PASSWORD=71f26894d16c0acc62defa4c841c90f2f2ae4716
ENV CONTAINER_APP_OUTPUT_DIR=/app/outputs








ENTRYPOINT ["python", "preprocess_data.py"]